[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gepa-legibility"
version = "0.1.0"
dependencies = [
	"dspy @ git+https://github.com/CDBiddulph/dspy.git",
	"python-dotenv",
	"uvicorn",
	"fastapi",
	"litellm",
	"peft",
	"transformers",
	"trl",
	"datasets",
	"tqdm",
	"vllm",
	"chz",
	"matplotlib",
	"numpy",
	"pandas",
	"pyyaml",
	"tinker",
	"tinker_cookbook @ git+https://github.com/thinking-machines-lab/tinker-cookbook.git",
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
	"pytest",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["core*", "tasks*", "run_gepa*", "run_rl*", "serving*"]
